### PR TITLE
add australian english dict

### PR DESCRIPTION
**Pull request by k-yle**
add dictionary for australian english

### CODE REVIEW

**Comment by aotaduy** [comment]
Is possible that you add some unit tests for this dictionary ? 
So we can test is working ok

**Comment by k-yle** [comment]
@aotaduy done, but [tests are failing across all branches](https://travis-ci.org/aotaduy/eslint-plugin-spellcheck/jobs/593037153#L4397); caused by `npm run performance`. this is not an issue with my PR.

**Comment by aotaduy** [comment]
Ok, let me fix that, and will come back to you.

**Comment by aotaduy** [comment]
Thanks for the PR sorry for the delay

**Pull request merged**
