### PR TITLE
Ignore file for npm pack

### LINKED ISSUE #27: Exclude files from npm package
In order to make downloads faster, exclude files that are not needed for the plugin to work from the npm package, such as the test files.

Currently the size of the npm package is 638 KB, via `npm pack` command.
While it is not huge, I will create a PR (#hacktoberfest) to see how much smaller it can get.

### PR DESCRIPTION
**Pull request by paazmaya**
Fixes #27, but with minimal benefit since there are only two test files at the moment, 638 KB --> 636 KB

### CODE REVIEW

**Comment by paazmaya** [comment]
@aotaduy any comments?

**Comment by aotaduy** [comment]
Sorry. looks good to me

**Comment by aotaduy** [comment]
Our main problem size problem is with the built in dictionaries. 
I like them because including them makes this package easy to install and use. I was using similar packages and install the dictionaries could be cumbersome and a no go when you are trying a plugin. Maybe I can do some changes to include only the default dictionary (en-us) and add some option to install the others.

**Comment by paazmaya** [comment]
Thank you!

**Pull request merged**
