### PR TITLE
omit module name in require statements

### LINKED ISSUE #45: Ability to omit spellchecking for names in imports
Hey, thanks for this plugin!

Is there a way to omit spellcheck in imports?

```
import classNames from 'classnames';
const merge = require('webpack-merge');
```

Both of the above are considered as problems by plugin.

### PR DESCRIPTION
**Pull request by tkharuk**
fixes #45
checks for require function.

### CODE REVIEW

**Comment by TuxujPes** [comment]
fixes #45 
checks for `require` function.

**Comment by sholsinger** [comment]
I submitted a PR to your fork @TuxujPes to add a configuration option for this functionality. Would you please accept and squash it into this PR?

**Comment by sholsinger** [comment]
@aotaduy It seems you disagree with including this functionality and would instead request that users apply an ignore word rule. (Based on the conversation in issue #45)

Given how simple and unobtrusive this PR is, does it really hurt the application to add it? Especially given the fact that there is already special handling for import declarations. I see this PR as we're merely allowing for the defacto standard import declaration to be supported and per your request, I've added a configuration option to make it optional.

**Comment by aotaduy** [comment]
Hi guys I was some time away from this project. Im mostly working on typescript now. Will try to keep up maintaining it. Thanks for the changes I think you are right about the feature not harming in any way the code. 
Thanks for The PR.

**Pull request merged**
