### PR TITLE
Make spell-checker rule compatible with ESLint 4+

### LINKED ISSUE #36: Comments are not checked in ESLint 4.11
I'm trying to update one of my projects from `ESLint@3.19` to the recent version: `4.11`

I noticed that spellchecker no longer checks comments

<table>
<tr>
<th>ESLint 3.19</th>
<th>ESLint 4.11</th>
</tr>
<tr>
<td>
screen shot 2017-11-22 at 14 33 37
</td>
<td>
screen shot 2017-11-22 at 14 32 26
</td>
</tr>
</table>
(green underline is WebStorm spellchecker)

### PR DESCRIPTION
**Pull request by jrencz**
Fix #36 

Tests now pass both on ESLint 3.19 and 4.11
I focused on making it work in ESLint 4 rather than preparing dual testing env so this PR does not contain any solution for testing on 2 versions of ESLint.

### CODE REVIEW

**Comment by aotaduy** [comment]
Hey @jrencz Thank you very much for your Pull request, I will review in a few days, I'm with a lot work right now, and I have some pending issues on this project. Im getting an error on travis for this PR Can you please check it out? 

Regards
Andres

**Comment by jrencz** [comment]
@aotaduy my bad. I assumed too recent node version. Fixed

**Comment by jrencz** [comment]
@aotaduy did you have a chance to take a look maybe?

**Comment by aotaduy** [comment]
Hi, Sorry for the delay in taking care of your pull request, and others, it is a very busy end of year for me with a newborn child in the family three months ago, I will try to find some time to review and merge your contribution. 

Regards

**Comment by jrencz** [comment]
Thanks for the reply.

>  it is a very busy end of year for me with a newborn child in the family three months ago

Congratulations!

I'd like to let you know that I published a pre-repease to my internal NPM-like private registry so this doesn't block me personally. On the other hand other users of the plugin may be blocked upgrading to eslint@4

**Comment by adammockor** [comment]
Is this possible to merge? Thank you!

**Pull request merged**
